# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific tag
trigger:
  tags:
    include:
    - '*'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: git submodule update --init --recursive
  displayName: 'Fetch third party dependency'

- script: |
    sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y
    sudo apt-get update -qq
    sudo apt-get -y install qt512base libgl1-mesa-dev qt512svg qt512imageformats
    source /opt/qt*/bin/qt*-env.sh
- task: CMake@1
  displayName: 'Generate make-files'
  inputs:
    cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release'


- script: cd $(Build.SourcesDirectory)/build && make -j 8
  displayName: 'Make'

- script: |
    source /opt/qt*/bin/qt*-env.sh
    cd $(Build.SourcesDirectory)/build
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
    chmod a+x linuxdeployqt*.AppImage
    export VERSION=$(git describe --abbrev=0)
    mv ../default.desktop . && mv ../icon.png .
    ./linuxdeployqt*.AppImage ./CPEditor -appimage
  displayName: 'Package to AppImage'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: github.com_coder3101
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    title: 'CP Editor'
    assets: $(Build.SourceDirecectory)/build/*.AppImage
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'