blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://cpeditor.org/docs/faq
    about: You may find your question and the answer to it here.
  - name: Documentation
    url: https://cpeditor.org/docs
    about: The documentation tells you how to use CP Editor.
  - name: Telegram Group
    url: https://t.me/cpeditor
    about: You can ask questions except for feature requests and bug reports here.
  - name: Slack Workspace
    url: https://join.slack.com/t/cpeditor/shared_invite/zt-ekfy0zb5-SrOi8SIox8oq61oRonBynw
    about: You can ask questions except for feature requests and bug reports in the "help" channel.
